#
#    $HeadURL$
#
#    $Revision$
#    $Date$
#
#    $Author$
#
#    Copyright (c) 2009,2010 California Institute of Technology.
#    All rights reserved.
#

JRUBY ?= jruby
JRUBY_CMD ?= $(JRUBY) --headless
MAKE_MAKEFILE ?= ../tools/make-makefile

Makefile: Makefile.erb
	@echo $< '->' $@
	@$(JRUBY_CMD) $(MAKE_MAKEFILE) $< > .$@ && mv .$@ $@