#!/usr/bin/env ruby

#--
#
# Copyright 2016 California Institute of Technology ("Caltech").
# U.S. Government sponsorship acknowledged.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
#++

# analyze-makefile reads a Makefile and one or more dependency files and produces an SVG graph of all targets and their predecessors.
# Input comes from files named on the command line and/or standard input. Output is named "analyze-makefile.svg".

require 'guid'
require 'yaml'
require 'graphviz'

class Array
  def paths(pr_hash)
  end
end

prereqs_by_target = {}
id_by_name = {}
phony = []
paths = []
edge = {}

TARGET_PAT = /^([[:alnum:].][^:]*):([^;=].*$)/
PHONY_PAT = /^\.PHONY:\s+(.*)$/

data = ARGF.read.gsub(/\\\n/m, ' ')
data.each_line do |line|
  if match = line.match(PHONY_PAT)
    phony += match[1].strip.split
  elsif match = line.match(TARGET_PAT)
    target = match[1]
    prereqs = match[2].strip.split
    prereqs_by_target[target] = prereqs
  end
end
phony.each do |p|
  prereqs_by_target.delete(p)
end

g = GraphViz.new('G', (p = ENV['GRAPHVIZ_PATH']) ? { :path => p } : {})
g['rankdir'] = 'LR'
g['overlap'] = 'scale'
g['sep'] = "0.4, 0.2"
g.node['shape'] = 'record'
g.node['fontname'] = 'Arial'
g.node['fontsize'] = '8.0'
g.edge['fontname'] = 'Arial'
g.edge['fontsize'] = '7.0'
  
prereqs_by_target.each do |target, prereqs|
  (prereqs.dup << target).each do |name|
    unless id_by_name[name]
      id = id_by_name[name] = 'node_' + name.gsub(/[.:-]/, '_')
      g.add_node(id, {:label => name})
    end
  end
  prereqs.each do |prereq|
    g.add_edge(id_by_name[prereq], id_by_name[target])
  end
end

g.output('svg' => 'analyze-makefile.svg')