#!/usr/bin/env ruby

#--
#
# Copyright 2016 California Institute of Technology ("Caltech").
# U.S. Government sponsorship acknowledged.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
#++

# extract-ontology retrieves an ontology from Fuseki by IRI and serializes it on standard output.

require 'JenaApplication'

APPLICATION_NAME = 'extract-ontology'

class ExtractApplication < JenaApplication
  
  def run
    
    super
    
    unless uri = argv.shift
      log(FATAL, 'no URI given')
      return 1
    end
    
    # Create model for result.
    
    log(INFO, 'create model for result')
    model = ModelFactory.create_default_model
    model.setNsPrefixes(@namespace_by_prefix)
    
    # Add model for named graph.
    
    log(DEBUG, "get model #{uri}")
    m = @data_service.get_model(uri)
    if m
      log(DEBUG, "add model #{uri}")
      model.add(m)
    end
    
    # Write model.
    
    log(INFO, 'write model')
    model.write(STDOUT.to_outputstream)
    
    # Exit.
    
    return 0
    
  end
end

exit(ExtractApplication.new(APPLICATION_NAME).start)
