#!/usr/bin/env ruby

#
# Copyright 2016 California Institute of Technology ("Caltech").
# U.S. Government sponsorship acknowledged.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

# get-unsat-iris reads the JUnit file resulting from running validate-owl
# and produces a CSV file with the IRIs for each unsatisfiable class.

require 'csv'
require 'fileutils'
require 'rexml/document'

csv = CSV.new(STDOUT)
csv << %w{ class }

doc = REXML::Document.new(ARGF)
top = doc.get_elements('testsuites/testsuite[@name="satisfiability"]').first
top.each_element('testcase') do |e|
  next unless failure = e.get_elements('failure').first
  name = e.attributes['name']
  klass = name.split[1].sub(/\A<(.*)>\z/, '\1')
  csv << [klass]
end
