#!/bin/sh

#
#    $HeadURL$
#
#    $LastChangedRevision$
#    $LastChangedDate$
#
#    $LastChangedBy$
#
#    Copyright (c) 2008-2014 California Institute of Technology.
#    All rights reserved.
#

aspell --mode sgml \
    --home-dir=$(dirname $0)/../lib/aspell \
    --personal aspell.en.pws --repl aspell.en.prepl \
    "$@"
